apiVersion: v1
kind: Service
metadata:
  name: postgrest
  labels:
    app.kubernetes.io/instance: postgrest
    app.kubernetes.io/name: postgrest
    helm.sh/chart: postgui-0.1.0
spec:
  type: {{ .Values.postgrest.service.type }}
  ports:
    - port: {{ .Values.postgrest.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: postgrest
    app.kubernetes.io/name: postgrest