apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgres"
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/version: 10.0.0
    helm.sh/chart: postgui-0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: postgres
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          stdin: true
          tty: true
          ports:
            - name: psql
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          resources: {}